
import Head from 'next/head'
import { Container, Nav, Navbar } from "react-bootstrap";
import { ReactNode } from 'react';
import NavbarMenu from '@/pages/components/NavbarMenu'

  type MyComponentProps = {
    children: ReactNode;
  }
  
  const MyComponent:React.FC<MyComponentProps> = ({ children }) => {
    return (
        <Container style={{ width:"1000px" }}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <script src="https://kit.fontawesome.com/fbadad80a0.js"crossOrigin="anonymous"></script>
            </Head>
            <header>
                <NavbarMenu/>
            </header>
            <main>{children}</main>
        </Container>
        )
  };
  
  export default MyComponent;